### ISSUE TITLE
Do not sort by ID (and in particular, not alphabetically when they are numbers)

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexibank#14]
Currently, languages and concepts are sorted by ID by default.

 - [ ] Languages should, by default, be sorted by language name.
 - [x] Concepts should get 0-padded numerical IDs, so they can be sorted according to occurrence in our word lists, instead of 1, 10, 100, 101, …

**Comment by OwenAmarasi** [comment]
I think this is fixed.
