### ISSUE TITLE
Revise example citation on the Home page

### ISSUE THREAD

**Issue by klamermaf** [Anaphory/lexibank#15]
From the Home page:

LINKED_REFERENCE_OBJECT. In: Kaiping, Gereon & Klamer, Marian (eds.) LexiRumah. Leiden: Leiden University Centre for Linguistics, 2017. Available online at http://model-ling.eu/fcgi-bin/lexibank/. Accessed on 2017-05-29.

The words in capitals should go, and instead of this citation (which is the database itself) we need an example here of how to cite the original source, e.g. Keraf 1978 is cited as 'Keraf, Gregorius. 1978. Morfologi Dialek Lamalera. Jakarta: Universitas Indonesia Doctoral dissertation.'

**Comment by klamermaf** [comment]
I closed it but it isn't solved of course...

**Comment by klamermaf** [comment]
Hmmm I also reopened it now...

**Comment by Anaphory** [comment]
Done, it now programatically displays the first (according to some metric) reference. I still need to update the front page, but I'll do that when looking at some other things, as well.
