### ISSUE TITLE
ID of concepts

### ISSUE THREAD

**Issue by klamermaf** [Anaphory/lexibank#17]
If we keep the ID of the concepts as a number, then it is better to have it as 3 digits, e.g. 001, 010 etc.

**Comment by Anaphory** [comment]
Yes, this was mentioned by Hanna and Owen, as well. Sorry I hadn't opened an issue for it yet.

**Comment by Anaphory** [comment]
Actually, it's part of #14, so I had made a note of it, but it's good to keep track of it separately.
