### ISSUE TITLE
Language ID for Western Pantar

### ISSUE THREAD

**Issue by wujiang720** [Anaphory/lexibank#19]
While fixing the coordinates, I noticed that we got two language IDs for Western Pantar, lamm1241 and lamm1241-westp. lamm1241-westp is the one that is currently online. I think they essentially refer to the same variety with the data extracted from the same source (or person), so maybe we need to fix this somehow. 

lamm1241 already has a coordinate in languages.tsv, so for now i copied and pasted it for lamm1241-westp too.

At last, does the ID 'lamm' actually make sense for Western Pantar? I mean, it isn't a variety of lamaholot, is it?

**Comment by Anaphory** [comment]
I introduced the two IDs at some point to avoid some kind of confusion. I think it was indeed the same variety in two different TSV files, so yes, it makes possibly sense to unify them.

Western Pantar == Lamma has that ID in Glottolog: http://glottolog.org/resource/languoid/id/lamm1241

**Comment by Anaphory** [comment]
`lamm1241` has gone, we only have `lamm1241-westp` at the moment.
