### ISSUE TITLE
Add column for comments to words

### ISSUE THREAD

**Issue by klamermaf** [Anaphory/lexibank#22]

**Comment by Anaphory** [comment]
Subject to testing, this is https://github.com/Anaphory/lexibank/commit/4e717d829517737af532087b672f4c052a97ecce

**Comment by Anaphory** [comment]
@klamermaf In addition to a lot of `nan`s instead of empty comments (that's for me to sort out), several of the comments are obviously not written for public display and will need cleanup. I have made a note of that in https://github.com/lessersunda/lexirumah-data/issues/18.

**Comment by klamermaf** [comment]
Ok, thanks Gereon! How shall we deal with this? Is there a place where I can see the comments to get a feeling of what they look like and whether/how we can (re) move them?


Marian Klamer (mobile)


-------- Oorspronkelijk bericht --------
Van: Gereon Kaiping <notifications@github.com>
Datum: 09-06-17 17:31 (GMT+01:00)
Aan: Anaphory/lexibank <lexibank@noreply.github.com>
Cc: "Klamer, M.A.F." <M.A.F.Klamer@hum.leidenuniv.nl>, Mention <mention@noreply.github.com>
Onderwerp: Re: [Anaphory/lexibank] Add column for comments to words (#22)


@klamermaf<https://github.com/klamermaf> In addition to a lot of nans instead of empty comments (that's for me to sort out), several of the comments are obviously not written for public display and will need cleanup. I have made a note of that in lessersunda/lexirumah-data#18<https://github.com/lessersunda/lexirumah-data/issues/18>.

**Comment by Anaphory** [comment]
The column is now online. See for example http://localhost:6543/parameters/000#8/-9.193/124.801 in Teiwa-Lebang.

**Comment by Anaphory** [comment]
(Some of the comments in “Sky” need to go into the reference metadata, because they apply to the whole word list, not to some entry in it.)

**Comment by klamermaf** [comment]
Hi Gereon
I looked through the comments for sky, and for some other items. Fortunately not too much work:
- "nan" can go everywhere.
- The comments in the cell for 'sky' which relate to transcriptions can all go as well. There are just 7 cells in the comments for 'sky' that should be made empty because they contain statements about the transcription.

(They are kept in the original excel sheets with field notes so will not be lost).

Marian

________________________________
