### ISSUE TITLE
Download of xls by concept has different colums from shown online

### ISSUE THREAD

**Issue by klamermaf** [Anaphory/lexibank#23]

**Comment by Anaphory** [comment]
I sent an email to clld people, maybe there is an obvious way to do it the same in all three places (online, csv, xls)

**Comment by Anaphory** [comment]
Fixed by creating a new adapter. https://github.com/Anaphory/lexibank/commit/21643913ea05ba1ce7501ebc5e4aac32111b9125

It may be worth unifying adapters/datatables at some point but that's a separate issue.
