### ISSUE TITLE
alternative names

### ISSUE THREAD

**Issue by hannalotte** [Anaphory/lexibank#37]
Another alternative name for Lamaholot-Lerek would be **Eastern Atadei**

An alternative name for Lamaholot-Kalikasa would be **Central Lembata**
(maybe delete the comment _from Keraf_ for this word list, as most words are from my word list??, you may add: _Lamaholot from the villages of Kalikasa, Bakan and Lewaji_ as it is done for some other lects)

**Comment by OwenAmarasi** [comment]
I think alternative names are no longer a thing?
