### ISSUE TITLE
Dataset/Provider/Source confusing

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexibank#4]
Use “Reference” for all of these.

**Comment by Anaphory** [comment]
The gettext-based translation has still not arrived online. I should ask @xrotwang for a reminder on how to deal with the locales and force-update the `.po` file in my webspace.

**Comment by xrotwang** [comment]
You may have excluded the .mo files in .gitignore
Am 29.05.2017 17:50 schrieb "Gereon Kaiping" <notifications@github.com>:

**Comment by Anaphory** [comment]
No, your commit where they are re-included is present: https://github.com/Anaphory/lexibank/commit/54d2c760c3991eca461ab0ce6a418e24eabcafc8

**Comment by Anaphory** [comment]
The issue is resolved, but I should note down somewhere how the .po>.mo translation works using gettext.

**Comment by Anaphory** [comment]
This may not be the best place to note this down, but it's the best I can think of right now.

The titles in the menu on top of every page are generated as “translations” from the generic locale to `en` and therefore live inside `lexibank/locale/en/LC_MESSAGES`.
In that folder, `clld.po` is the human-editable description file. The standard way to generate such a file seems to be running `xgettext SOURCEFILE SOURCEFILE …`.
However, the file that actually controls Lexibank behaviour is the `.mo` file, which is generated using `msgfmt clld.po --output-file clld.mo`.

**Comment by xrotwang** [comment]
The standard way to use the translation mechanism is described here: http://clld.readthedocs.io/en/latest/extending.html#wording

**Comment by Anaphory** [comment]
Thank you! I should look into the clld docs more often, so that I can either find what I'm looking for or at least put it in there after I found out.
