### ISSUE TITLE
Discuss what information to display when you click on a word

### ISSUE THREAD

**Issue by OwenAmarasi** [Anaphory/lexibank#41]
At the moment, it just takes you to a display with the phonetic form (in angle brackets), the lect, the segmentation (in square brackets), the reference and any synonyms. It might be nice to have more information here, like the orthography.

**Comment by OwenAmarasi** [comment]
I guess we should have this discussion. Or if it is impossible to show other information we close this issue.

**Comment by Anaphory** [comment]
It is possible to show a lot of things, some easily, some with coding and/or computation effort.

**Comment by OwenAmarasi** [comment]
We discussed this so I'll make a new issue to implement what we discussed.
